# Generated by Django 4.2.2 on 2023-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Faild'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
