# Generated by Django 4.2.2 on 2023-06-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_weight_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
