# Generated by Django 4.2.2 on 2023-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_weight_delete_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(null=True, related_name='products', to='store.promotion'),
        ),
    ]
