# Generated by Django 4.2.2 on 2023-06-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(default='5%', related_name='products', to='store.promotion'),
        ),
    ]
